# Streamlit优化配置文件
# 将此文件放在项目根目录下命名为 .streamlit/config.toml

[global]
# 开发模式设置
developmentMode = false

[server]
# 服务器性能优化
maxUploadSize = 200
maxMessageSize = 200
enableCORS = false
enableXsrfProtection = true

# 启用文件监视器优化
fileWatcherType = "auto"

# WebSocket 优化
enableWebsocketCompression = true

[browser]
# 浏览器优化
gatherUsageStats = false
serverAddress = "localhost"

[runner]
# 运行时优化
magicEnabled = true
installTracer = false
fixMatplotlib = true

# 快速重新运行
fastReruns = true

[client]
# 客户端优化
caching = true
displayEnabled = true
showErrorDetails = true

[theme]
# 主题设置 (可选)
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"