[theme]
base="light"                         
primaryColor="#7f12a0ff"           
backgroundColor="#FFFFFF"           
secondaryBackgroundColor="#F0F2F6"  
textColor="#262730"                 
font="sans serif"    

[global]
developmentMode = false

[server]
maxUploadSize = 200
maxMessageSize = 200
enableCORS = false
enableXsrfProtection = true

fileWatcherType = "auto"

enableWebsocketCompression = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

fastReruns = true

[client]
caching = true
displayEnabled = true
showErrorDetails = true