[theme]
base="light"                         
primaryColor="#7f12a0ff"           
backgroundColor="#FFFFFF"           
secondaryBackgroundColor="#F0F2F6"  
textColor="#262730"                 
font="sans serif"                     