[theme]
base="light"                          # 或 "dark"
primaryColor="#7f12a0ff"            # 主颜色
backgroundColor="#FFFFFF"           # 页面背景色
secondaryBackgroundColor="#F0F2F6"  # 侧边栏背景色
textColor="#262730"                 # 正文文字颜色
font="sans serif"                     # 可选: "sans serif", "serif", "monospace"